### ISSUE TITLE
È IL NUMERO U, È IL NUMERO U

### ISSUE THREAD

**Issue by thaMilo** [rcastellotti/mannaggia#1]
https://www.facciabuco.com/post/155350ngp/san-ceppato-protettore-delle-stampanti-solo-per-nerd-post-by-nightfalldj.html

**Comment by fedfontana** [comment]
lgtm 👍🏼

**Comment by thaMilo** [comment]
![sanceppato](https://github.com/rcastellotti/mannaggia/assets/42500999/8055e66d-fb3f-4e4c-9c39-b9b686bb9a55)

**Comment by F4de78** [comment]
ci sta, emoji fuoco

**Comment by fedfontana** [comment]
@F4de78 emoji fuoco anche a te fratello 🔥

**Comment by rcastellotti** [comment]
mannaggia!
